### PR TITLE
Matrix/Vector methods

### PR DESCRIPTION
**Pull request by brason**
Ok, so I added some more methods from three.js. I only found tests for compose/decompose, so If you think some tests are in order, I would need some help with that. Also, I feel that maybe `Matrix4.compose` should be a constructor instead of a method. What do you think?

### CODE REVIEW

**Comment by Fox32** [comment]
I would always prefer a method over a constructor. That allows to reuse an existing instance. On the other side, also adding a factory constructor calling that method wouldn't be a big deal and would satisfy everyone.

The same applies for methods like getNormalMatrix. I would prefer a copyNormalMatrix where I can supply a destination matrix. But providing both methods would be possible if getNormalMatrix calls copyNormalMatrix without much additional code.

About the apply* methods: Some of them are already available in Matrix as transform*. I'm not sure if we should have them both as apply* and transform*. However, I also introduced perspectiveTransform some days ago and noticed later that there was already the right applyProjection method...

**Comment by brason** [comment]
I guess you're right about reusing an exisiting instance. But if I were to create a factory constructor calling compose, what should it be called?. 

Also, I added copyNormalMatrix as you suggested.

Regarding the apply methods, I would prefer doing this: `vector.applyMatrix4(matrix)`, over `matrix.transform3(vector)`, but I don't see a problem having both options. The main reason I want to add applyMatrix3 and applyMatrix4 is because they are heavily used in three.js, and three.dart uses vector_math.

**Comment by Fox32** [comment]
The first moment when I saw compose and decompose I thought about fromTranslationRotationScale and copyTranslationRotationScale but these are quite long names =D

**Comment by brason** [comment]
Yeah, those are pretty long cumbersome names indeed :) Maybe we should leave it like this for now.

**Comment by Fox32** [comment]
By the way, Matrix4 has a method called setFromTranslationRotation so the name is not that far off.

**Comment by brason** [comment]
Just as you know, moments before you merged I changed the compose method to setFromTranslationRotation and created a Matrix4.compose constructor instead.

**Comment by johnmccutchan** [comment]
Hi,

Can you send me a pull request?

**Comment by brason** [comment]
It seems like the change was included. Maybe I already had pushed the change before you merged.

**Pull request merged**
