### PR TITLE
Feature/cleanup

### PR DESCRIPTION
**Pull request by Fox32**
I started this pull request with the goal to remove call chaining (#59) but I also took a look at "some" other things:

* Remove call chaining (breaking change, but the Dart Editor gives very good guidance here!)
* Rename some parts to match the Dart Style guide (constants, constructors, ...) (I only deprecated them)
* Removed some methods that didn't provide a real benefit (e.g. Sphere.copyOriginDirection)
* Formatting
* Analyser warnings
* Remove duplicate code (e.g. the plus operator of a vector can share the same code as VectorN.add)
* Add more documentation comments (especially for the collision detection objects)
* Improve code in a way that dart2js can generate better code. I took [these](https://code.google.com/p/dart/issues/detail?id=17434#c2) suggestions as a start. Here is a example of dart2js code that changed, the old code:
```
dot$1: [function(other) {
      var t1, t2, t3, t4, t5, t6, t7;
      t1 = this.storage;
      t2 = t1[0];
      t3 = other.get$storage();
      t4 = t3.length;
      if (0 >= t4)
        return H.ioore(t3, 0);
      t5 = t3[0];
      t6 = t1[1];
      if (1 >= t4)
        return H.ioore(t3, 1);
      t7 = t3[1];
      t1 = t1[2];
      if (2 >= t4)
        return H.ioore(t3, 2);
      return t2 * t5 + t6 * t7 + t1 * t3[2];
    }, "call$1", "get$dot", 2, 0, null, 109, []],
```
and the new code:
```
    dot$1: [function(other) {
      var otherStorage, t1;
      otherStorage = other.get$_storage();
      t1 = this._storage;
      return t1[0] * otherStorage[0] + t1[1] * otherStorage[1] + t1[2] * otherStorage[2];
    }, "call$1", "get$dot", 2, 0, null, 109, []],
```
In this case range checks could be removed, in other cases less calls to getters are made. It also has a small influence on code size, but I don't think that these are significant. For the future it would be nice to have a test bench to compare the performance of changes in both the DartVM and Dart2Js. Not sure what to choose as a benchmark here, maybe some sort of simulation?

### CODE REVIEW

**Comment by Fox32** [comment]
@johnmccutchan 

My plan is to wait until the bigger cleanup PR by others are finished. Currently merge conflicts are too annoying. Especially the formatting and  Then my plan is to do get vector_math back on a similar level as my fork. But I would prefer to make feature centered PRs, here is my plan:

##### The dart2js related performance improvments:
- [ ] Different private field names for each datatype (https://code.google.com/p/dart/issues/detail?id=17434#c2)
- [ ] Split code in each class into two layers: the lower one works on the typed data lists directly this allows for more dart2js optimization (https://code.google.com/p/dart/issues/detail?id=17434#c6))

##### Cleanup:
- [ ] Move matrix_bench to benchmark folder

##### Fix bugs
- [ ] #88 
- [ ] https://github.com/Fox32/vector_math/commit/792ed45e139a1381218a7b1c3199c2856ed72df7

##### Performance changes:
- [ ] https://github.com/Fox32/vector_math/commit/30b9cc46e8f0e864b20db9c95bf0e14cd872c2d1
- [ ] https://github.com/Fox32/vector_math/commit/3620aa8cb86c3aa0cfc46d1b4e57598387f7634b
- [ ] https://github.com/Fox32/vector_math/commit/af108af64acabfd4731fe1b4d727d8ea9b1e975b
- [ ] https://github.com/Fox32/vector_math/commit/1a2ba8f59a79e760fa0da042157b6286a6452c7e

##### Features like:
- [ ] OBB, 
- [ ] Triangle, 
- [ ] Quad (how to make triangle and quad more memory efficient? They are quite huge in dart2js)

##### Maybe remove call chaining?

##### Much later: documentation improvements

##### And all the things I missed...

**Comment by kevmoo** [comment]
I like it, @Fox32.

Keep an eye on the new Box2d library as you move forward - https://github.com/google/box2d.dart

**Comment by kevmoo** [comment]
@Fox32 Do you have plans to track performance changes for these tweaks?

**Comment by Fox32** [comment]
@kevmoo I think I try to do the performance things later, but that Box2d would be a nice benchmark for some of the core classes, sadly Box2d isn't covering much of vector_math.
Beside that I would try to reduce the amount of type and bounds checks of the generade javascript code.

Do you have any bigger changes to vector_math in the pipeline?

**Comment by kevmoo** [comment]
@Fox32 Nope.

**Comment by kevmoo** [comment]
@Fox32 Keep things formatted using `dartfmt` with each of your commits so we can keep style-related churn to a minimum

**Comment by Fox32** [comment]
@kevmoo @johnmccutchan 
I updated the list above with my current progress. I think we have enough PRs for now and I will wait till all are review, corrected, and merged. I starting to have dependencies between the PRs that makes further work to complicated for now.

**Comment by Fox32** [comment]
Everything, except call chaining, is now included \o/
I will close this one.

**Comment by johnmccutchan** [comment]
@Fox32 Thank you very much for your great work. Looking forward to 2.0 without call chaining.

**Pull request closed without merging**
