### PR TITLE
Add obb3 class

### PR DESCRIPTION
**Pull request by Fox32**
Basic obb3 class with some common methods and intersection tests.

### CODE REVIEW

**Comment by kevmoo** [comment]
@Fox32 Care to rebase and clean this up?

**Comment by Fox32** [comment]
I rebased this but there were no conflicts?

**Comment by kevmoo** [comment]
@Fox32 I'm sorry, I mean rebase and flatten. `git rebase -i <johnsrepo/master>`

So the commit history is nice and clean. :smile:

**Comment by Fox32** [comment]
Done :)

**Comment by kevmoo** [comment]
Shouldn't this be one commit?

**Comment by Fox32** [comment]
This time it is all squashed

**Pull request merged**
