### PR TITLE
Use unique names for private storage fields in Vector(2,3,4), Matrix(2,3,4)

### LINKED ISSUE #126: Rename _storage private field to be different in each class
Vector2: _v2st
Vector3: _v3st

Matrix2: _m2st
Matrix3: _m3st

etc

Will help dart2js create smaller code

CC @Fox32

### PR DESCRIPTION
**Pull request by kevmoo**
Fixes #126

### CODE REVIEW

**Comment by Fox32** [comment]
Can we do #132 first and then redo this one? Some code that was later added uses the public getter instead of the private variables

**Comment by kevmoo** [comment]
@Fox32 Done. Rebased

**Comment by Fox32** [comment]
Looks good, but misses vector_math_64

**Comment by kevmoo** [comment]
Ooops. Fixed. Thanks.

**Pull request merged**
