### PR TITLE
Float32ListView

### PR DESCRIPTION
**Pull request by Fox32**
#81 Implement a view for Float32List that allows to specify a stride and an offset.

I'm open for a better name than Float32ListView, however Vector1List might implie that it implements VectorList which it doesn't do (as it is not possible).

### CODE REVIEW

**Comment by johnmccutchan** [comment]
Hi,

Also a Float64ListView?

**Comment by Fox32** [comment]
I'm thinking about a vector_math_64 library in the future that is generated. But that a more generic name would be better.

**Comment by johnmccutchan** [comment]
ScalarListView ?

**Comment by Fox32** [comment]
@johnmccutchan I like ScalarListView and updated the PR with it

**Pull request merged**
